//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeraSoft.Resources.Properties {
    //using PropertyChanged;
    using System.Threading;


    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    //[AddINotifyPropertyChangedInterface]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture = Thread.CurrentThread.CurrentUICulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VeraSoft.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a april.
        /// </summary>
        public static string april {
            get {
                return ResourceManager.GetString("april", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a august.
        /// </summary>
        public static string august {
            get {
                return ResourceManager.GetString("august", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Changes saved.
        /// </summary>
        public static string ChangesSaved {
            get {
                return ResourceManager.GetString("ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a december.
        /// </summary>
        public static string december {
            get {
                return ResourceManager.GetString("december", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destination.
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exported sucessfully.
        /// </summary>
        public static string ExportedOk {
            get {
                return ResourceManager.GetString("ExportedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a february.
        /// </summary>
        public static string february {
            get {
                return ResourceManager.GetString("february", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Files export.
        /// </summary>
        public static string FilesExport {
            get {
                return ResourceManager.GetString("FilesExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a january.
        /// </summary>
        public static string january {
            get {
                return ResourceManager.GetString("january", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a july.
        /// </summary>
        public static string july {
            get {
                return ResourceManager.GetString("july", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a june.
        /// </summary>
        public static string june {
            get {
                return ResourceManager.GetString("june", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language was changed sucessfully.
        /// </summary>
        public static string LanguageChangedOK {
            get {
                return ResourceManager.GetString("LanguageChangedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a march.
        /// </summary>
        public static string march {
            get {
                return ResourceManager.GetString("march", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximize.
        /// </summary>
        public static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a may.
        /// </summary>
        public static string may {
            get {
                return ResourceManager.GetString("may", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimize.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Music.
        /// </summary>
        public static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a november.
        /// </summary>
        public static string november {
            get {
                return ResourceManager.GetString("november", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a october.
        /// </summary>
        public static string october {
            get {
                return ResourceManager.GetString("october", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organize your documents.
        /// </summary>
        public static string Organizer {
            get {
                return ResourceManager.GetString("Organizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Photos.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save by date.
        /// </summary>
        public static string SaveByDate {
            get {
                return ResourceManager.GetString("SaveByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select your language.
        /// </summary>
        //[PropertyChanged.AlsoNotifyFor("Culture")]
        //[PropertyChanged.DependsOn("Culture")]
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a theme to the app.
        /// </summary>
        public static string SelectTheme {
            get {
                return ResourceManager.GetString("SelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select what to save.
        /// </summary>
        public static string SelectWhatToSave {
            get {
                return ResourceManager.GetString("SelectWhatToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a september.
        /// </summary>
        public static string september {
            get {
                return ResourceManager.GetString("september", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Videos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
    }
}
